server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.88.134
    username: dean
    password: 123456
    virtual-host: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  static:
    itemDir: F:\GitHub\leyouItemHtml\item
    itemTemplate: item