server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    registry-fetch-interval-seconds: 5 # 服务拉取周期
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  prefix: /api #网关的前缀
  routes:
    item-service: /item/** #网关的路由映射
    search-service: /search/** #search搜索服务映射
    upload-service: /upload/** #上传搜索服务映射
    user-service: /user/** #user服务映射
    auth-service: /auth/**
    order-service:
      path: /order/**
      serviceId: order-service
      strip-prefix: false
    cart-service:
      path: /cart/**
      serviceId: cart-service
      strip-prefix: false
  sensitive-headers:  #覆盖敏感头信息 不拦截用户token

ly:
  cors:
    allowedOrigins:
     - http://manage.leyou.com
     - http://www.leyou.com
    allowedCredentials: true
    allowedHeaders:
     - "*"
    allowedMethods:
     - GET
     - POST
     - DELETE
     - PUT
     - OPTIONS
     - HEAD
    maxAge: 360000
    filterPath: "/**"
  jwt:
    pubKeyPath: F:/GitHub/authUser/develop/ssh/id_rsa.pub # 公钥地址
    user:
      cookieName: LY_TOKEN # cookie名称
    app:
      id: 7 # 服务id
      secret: ${spring.application.name} # 服务密钥，默认是服务的名称
      headerName: privilege_token
  filter:
    allowPaths:
      - /api/auth/login
      - /api/search/page
      - /api/search/filter
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
