server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.88.134
  rabbitmq:
    host: 192.168.88.134
    username: dean
    password: 123456
    virtual-host: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.user.bean
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.leyou: debug
ly:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 4 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加