server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 192.168.88.134
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    pubKeyPath: F:/GitHub/authUser/develop/ssh/id_rsa.pub # 公钥地址
    priKeyPath: F:/GitHub/authUser/develop/ssh/id_rsa # 私钥地址
    user:
      expire: 30 # 过期时间,单位分钟
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
      minRefreshInterval: 600000 # 刷新的最小时间毫秒，10分钟
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 10
