server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
  rabbitmq:
    host: 192.168.88.134
    username: dean
    password: 123456
    virtual-host: leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
    publisher-confirms: true
  redis:
    host: 192.168.88.134
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    com.leyou: debug
mybatis:
  type-aliases-package: com.leyou.bean
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml
mapper:
  wrap-keyword: "`{0}`"